import { GoogleGenAI, Type } from '@google/genai';
import { CandidateFinding } from './types.js';
import { trackGeminiCall } from './usage.js';

export class DeduplicatorAgent {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  }

  async deduplicate(findings: CandidateFinding[]): Promise<CandidateFinding[]> {
    if (!findings || findings.length === 0) return [];

    // Fallback if deduplicator is disabled via config
    if (process.env.USE_DEDUPLICATOR === 'false') {
       return findings;
    }

    try {
      console.log(`[Deduplicator] Starting deduplication of ${findings.length} findings...`);
      const systemInstruction = `You are an expert Code Review Deduplicator agent.
You will be provided with a JSON array of code review findings mapped to specific files and lines. These findings were generated by various specialist subagents, so many of them will overlap or highlight the exact same issue from slightly different angles.

Your job is to read all the findings and rigorously MERGE them into a single, cohesive, deduplicated JSON array.

Follow this step-by-step process:
1. **Identify Groups**: Group findings that target the SAME or NEARBY lines (within 10 lines) in the SAME file, AND they relate to the same root cause or issue.
2. **Merge Groups**: For each group of related findings, synthesize them into a SINGLE CandidateFinding.
    * **Summary**: Create a concise summary that captures the core issue.
    * **Description**: Combine the descriptions from all findings in the group into a comprehensive explanation of the problem and its impact (e.g., explain that it is a performance issue AND a security risk).
    * **Suggestion**: Provide the best, most comprehensive code suggestion or remediation steps.
    * **Severity**: Take the highest severity among the findings in the group.
    * **Agent**: Concatenate the agent names with commas (e.g., 'Performance, Security').
3. **Keep Distinct Findings**: Findings that do not share a root cause with others should be kept separate.

Your final output MUST match the schema of an array of CandidateFinding objects.
CRITICAL: You MUST retain the 'agent' field for every single finding. Without this, the UI breaks.`;

      const startTime = Date.now();
      console.log(`[Deduplicator] Sending request to Gemini...`);
      
      const deduplicatorModel = process.env.DEDUPLICATOR_MODEL || 'gemini-3.1-pro-preview';
      const request = trackGeminiCall(
        { callType: 'deduplicate', model: deduplicatorModel },
        () => this.ai.models.generateContent({
        model: deduplicatorModel,
        contents: JSON.stringify(findings),
        config: {
          systemInstruction,
          // Without an explicit cap, this model can pathologically hang past
          // Node's 5-minute headers timeout with ZERO response when the
          // input findings are highly repetitive/near-duplicate (e.g. the
          // same pattern flagged at several similar call sites) — confirmed
          // via a standalone repro outside the app. Root cause isn't excess
          // latency from thinking itself: an 8192 cap still hung; 4096 and
          // below reliably completed in ~12-17s on the same repetitive
          // input. This model rejects thinkingBudget: 0 (requires "thinking
          // mode"), so 4096 is the smallest well-tested safe floor, with
          // ~1.8x headroom above the ~2200 thinking tokens a healthy
          // 12-finding merge used natively.
          thinkingConfig: { thinkingBudget: 4096 },
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.ARRAY,
            description: "A consolidated list of deduplicated code review findings.",
            items: {
              type: Type.OBJECT,
              properties: {
                file: { type: Type.STRING },
                line: { type: Type.INTEGER },
                severity: { type: Type.STRING, enum: ["CRITICAL", "HIGH", "MEDIUM", "LOW"] },
                summary: { type: Type.STRING },
                description: { type: Type.STRING },
                suggestion: { type: Type.STRING, nullable: true },
                agent: { type: Type.STRING, nullable: true }
              },
              required: ["file", "line", "severity", "summary", "description"]
            }
          }
        }
        })
      );

      // Node's setTimeout treats NaN, <=0, and anything above the 32-bit
      // signed int max (2147483647) identically: it clamps to ~1ms and
      // fires almost immediately (verified empirically — see the PR
      // description) — so every dedup call would "time out" instantly
      // under any of those GEMINI_TIMEOUT_MS values. Fall back to the
      // existing 300000 default (matches agent.ts's own guard).
      const rawTimeoutMs = parseInt(process.env.GEMINI_TIMEOUT_MS || '300000', 10);
      const timeoutMs = Number.isNaN(rawTimeoutMs) || rawTimeoutMs <= 0 || rawTimeoutMs > 2147483647 ? 300000 : rawTimeoutMs;
      console.log(`[Deduplicator] Timeout set to ${timeoutMs}ms`);
      
      let timeoutId: NodeJS.Timeout | undefined;
      const timeoutPromise = new Promise<any>((_, reject) => {
          timeoutId = setTimeout(() => reject(new Error(`ETIMEDOUT: Deduplicator fetch exceeded ${timeoutMs}ms.`)), timeoutMs);
      });

      const response = await Promise.race([request, timeoutPromise]).finally(() => clearTimeout(timeoutId));
      
      const duration = Date.now() - startTime;
      console.log(`[Deduplicator] Response received in ${duration}ms`);
      
      if (response.usageMetadata) {
         console.log(`[Deduplicator] Tokens used - Prompt: ${response.usageMetadata.promptTokenCount}, Candidates: ${response.usageMetadata.candidatesTokenCount}`);
      }

      if (response.text) {
        const mergedFindings = JSON.parse(response.text) as CandidateFinding[];
        console.log(`[Deduplicator] Successfully deduplicated into ${mergedFindings.length} findings.`);
        return mergedFindings;
      }

      console.warn(`[Deduplicator] Empty response. Returning raw findings.`);
      return findings;

    } catch (e) {
      console.error("[Deduplicator] Failed to deduplicate findings:", e);
      return findings;
    }
  }
}
