import { GoogleGenAI, Type } from '@google/genai';
import { CandidateFinding } from './types.js';

export class DeduplicatorAgent {
  private ai: GoogleGenAI;

  constructor() {
    const useVertex = process.env.USE_VERTEX_AI === 'true';
    if (useVertex) {
      this.ai = new GoogleGenAI({});
    } else {
      this.ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    }
  }

  async deduplicate(findings: CandidateFinding[]): Promise<CandidateFinding[]> {
    if (!findings || findings.length === 0) return [];
    
    // Fallback if deduplicator is disabled via config
    if (process.env.USE_DEDUPLICATOR === 'false') {
       return findings;
    }

    try {
      console.log(`[Deduplicator] Starting deduplication of ${findings.length} findings...`);
      const systemInstruction = `You are an expert Code Review Deduplicator agent.
You will be provided with a JSON array of code review findings mapped to specific files and lines. These findings were generated by various specialist subagents, so many of them will overlap or highlight the exact same issue from slightly different angles.

Your job is to read all the findings and rigorously MERGE them into a single, cohesive, deduplicated JSON array.
Rules:
1. If multiple agents flagged the same line/file with related architectural or bugs, merge their descriptions and suggestions into ONE comprehensive finding, taking the highest severity.
2. If findings are entirely distinct, keep them separate.
3. Your final output MUST match the schema of an array of CandidateFinding objects.`;

      const request = this.ai.models.generateContent({
        model: process.env.DEDUPLICATOR_MODEL || 'gemini-2.5-flash',
        contents: JSON.stringify(findings),
        config: {
          systemInstruction,
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.ARRAY,
            description: "A consolidated list of deduplicated code review findings.",
            items: {
              type: Type.OBJECT,
              properties: {
                file: { type: Type.STRING },
                line: { type: Type.INTEGER },
                severity: { type: Type.STRING, enum: ["CRITICAL", "HIGH", "MEDIUM", "LOW"] },
                summary: { type: Type.STRING },
                description: { type: Type.STRING },
                suggestion: { type: Type.STRING, nullable: true },
                agent: { type: Type.STRING, nullable: true } 
              },
              required: ["file", "line", "severity", "summary", "description"]
            }
          }
        }
      });

      const timeoutMs = parseInt(process.env.GEMINI_TIMEOUT_MS || '180000', 10);
      let timeoutId: NodeJS.Timeout | undefined;
      const timeoutPromise = new Promise<any>((_, reject) => {
          timeoutId = setTimeout(() => reject(new Error(`ETIMEDOUT: Deduplicator fetch exceeded ${timeoutMs}ms.`)), timeoutMs);
      });

      const response = await Promise.race([request, timeoutPromise]).finally(() => clearTimeout(timeoutId));
      
      if (response.usageMetadata) {
         console.log(`[Deduplicator] Tokens used - Prompt: ${response.usageMetadata.promptTokenCount}, Candidates: ${response.usageMetadata.candidatesTokenCount}`);
      }

      if (response.text) {
        const mergedFindings = JSON.parse(response.text) as CandidateFinding[];
        console.log(`[Deduplicator] Successfully deduplicated into ${mergedFindings.length} findings.`);
        return mergedFindings;
      }

      console.warn(`[Deduplicator] Empty response. Returning raw findings.`);
      return findings;

    } catch (e) {
      console.error("[Deduplicator] Failed to deduplicate findings:", e);
      return findings;
    }
  }
}
