import { GoogleGenAI, Type } from '@google/genai';
import * as fs from 'fs';
import * as path from 'path';

async function main() {
  const jsonPath = process.argv[2];
  if (!jsonPath) {
    console.error("Please provide path to findings JSON file.");
    process.exit(1);
  }

  const findings = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  console.log(`Read ${findings.length} findings from ${jsonPath}`);

  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

  const systemInstruction = `You are an expert Code Review Deduplicator agent.
You will be provided with a JSON array of code review findings mapped to specific files and lines. These findings were generated by various specialist subagents, so many of them will overlap or highlight the exact same issue from slightly different angles.

Your job is to read all the findings and rigorously MERGE them into a single, cohesive, deduplicated JSON array.

Follow this step-by-step process:
1. **Identify Groups**: Group findings that target the SAME or NEARBY lines (within 10 lines) in the SAME file, AND they relate to the same root cause or issue.
2. **Merge Groups**: For each group of related findings, synthesize them into a SINGLE CandidateFinding.
    * **Summary**: Create a concise summary that captures the core issue.
    * **Description**: Combine the descriptions from all findings in the group into a comprehensive explanation of the problem and its impact (e.g., explain that it is a performance issue AND a security risk).
    * **Suggestion**: Provide the best, most comprehensive code suggestion or remediation steps.
    * **Severity**: Take the highest severity among the findings in the group.
    * **Agent**: Concatenate the agent names with commas (e.g., 'Performance, Security').
3. **Keep Distinct Findings**: Findings that do not share a root cause with others should be kept separate.

Your final output MUST match the schema of an array of CandidateFinding objects.
CRITICAL: You MUST retain the 'agent' field for every single finding. Without this, the UI breaks.`;

  console.log("[Test] Calling Gemini...");
  const response = await ai.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: JSON.stringify(findings),
    config: {
      systemInstruction,
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.ARRAY,
        description: "A consolidated list of deduplicated code review findings.",
        items: {
          type: Type.OBJECT,
          properties: {
            file: { type: Type.STRING },
            line: { type: Type.INTEGER },
            severity: { type: Type.STRING, enum: ["CRITICAL", "HIGH", "MEDIUM", "LOW"] },
            summary: { type: Type.STRING },
            description: { type: Type.STRING },
            suggestion: { type: Type.STRING, nullable: true },
            agent: { type: Type.STRING, nullable: true }
          },
          required: ["file", "line", "severity", "summary", "description"]
        }
      }
    }
  });

  console.log("[Test] Response received!");
  if (response.text) {
    console.log(response.text);
    const merged = JSON.parse(response.text);
    console.log(`[Test] Deduplicated into ${merged.length} findings.`);
  } else {
    console.log("[Test] Empty response!");
  }
}

main().catch(console.error);
